include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    constant_identifier_names: false
    # Pozwalamy na ify bez klamerek {}
    curly_braces_in_flow_control_structures: false
    non_constant_identifier_names: false
    # Pozwalamy na print() (choć lepiej unikać, w dev jest ok)
    avoid_print: false
    # Pozwalamy na nieużywanie const w konstruktorach (to tylko optymalizacja)
    prefer_const_constructors: false
    # Pozwalamy na zmianę nazw parametrów w metodach nadpisanych
    avoid_renaming_method_parameters: false